language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - go get github.com/jteeuwen/go-bindata/...
  - get github.com/elazarl/go-bindata-assetfs/...