name: Go
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.16', '1.15', '1.14' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: TwitterGeo go-${{ matrix.go }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build -v .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: TwitterGeo go-${{ matrix.go }}-${{ matrix.os }}
          path: ${{ matrix.os == 'windows-latest' && 'twittergeo.exe' || 'twittergeo' }}
